// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cc/cc/query.proto

package cc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName             = "/cc.cc.Query/Params"
	Query_ShowExchange_FullMethodName       = "/cc.cc.Query/ShowExchange"
	Query_ListExchange_FullMethodName       = "/cc.cc.Query/ListExchange"
	Query_ListSenderExchange_FullMethodName = "/cc.cc.Query/ListSenderExchange"
	Query_ListDateExchange_FullMethodName   = "/cc.cc.Query/ListDateExchange"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ShowExchange items.
	ShowExchange(ctx context.Context, in *QueryShowExchangeRequest, opts ...grpc.CallOption) (*QueryShowExchangeResponse, error)
	// Queries a list of ListExchange items.
	ListExchange(ctx context.Context, in *QueryListExchangeRequest, opts ...grpc.CallOption) (*QueryListExchangeResponse, error)
	// Queries a list of ListSenderExchange items.
	ListSenderExchange(ctx context.Context, in *QueryListSenderExchangeRequest, opts ...grpc.CallOption) (*QueryListSenderExchangeResponse, error)
	// Queries a list of ListDateExchange items.
	ListDateExchange(ctx context.Context, in *QueryListDateExchangeRequest, opts ...grpc.CallOption) (*QueryListDateExchangeResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowExchange(ctx context.Context, in *QueryShowExchangeRequest, opts ...grpc.CallOption) (*QueryShowExchangeResponse, error) {
	out := new(QueryShowExchangeResponse)
	err := c.cc.Invoke(ctx, Query_ShowExchange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListExchange(ctx context.Context, in *QueryListExchangeRequest, opts ...grpc.CallOption) (*QueryListExchangeResponse, error) {
	out := new(QueryListExchangeResponse)
	err := c.cc.Invoke(ctx, Query_ListExchange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListSenderExchange(ctx context.Context, in *QueryListSenderExchangeRequest, opts ...grpc.CallOption) (*QueryListSenderExchangeResponse, error) {
	out := new(QueryListSenderExchangeResponse)
	err := c.cc.Invoke(ctx, Query_ListSenderExchange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDateExchange(ctx context.Context, in *QueryListDateExchangeRequest, opts ...grpc.CallOption) (*QueryListDateExchangeResponse, error) {
	out := new(QueryListDateExchangeResponse)
	err := c.cc.Invoke(ctx, Query_ListDateExchange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ShowExchange items.
	ShowExchange(context.Context, *QueryShowExchangeRequest) (*QueryShowExchangeResponse, error)
	// Queries a list of ListExchange items.
	ListExchange(context.Context, *QueryListExchangeRequest) (*QueryListExchangeResponse, error)
	// Queries a list of ListSenderExchange items.
	ListSenderExchange(context.Context, *QueryListSenderExchangeRequest) (*QueryListSenderExchangeResponse, error)
	// Queries a list of ListDateExchange items.
	ListDateExchange(context.Context, *QueryListDateExchangeRequest) (*QueryListDateExchangeResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) ShowExchange(context.Context, *QueryShowExchangeRequest) (*QueryShowExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowExchange not implemented")
}
func (UnimplementedQueryServer) ListExchange(context.Context, *QueryListExchangeRequest) (*QueryListExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExchange not implemented")
}
func (UnimplementedQueryServer) ListSenderExchange(context.Context, *QueryListSenderExchangeRequest) (*QueryListSenderExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSenderExchange not implemented")
}
func (UnimplementedQueryServer) ListDateExchange(context.Context, *QueryListDateExchangeRequest) (*QueryListDateExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDateExchange not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShowExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowExchange(ctx, req.(*QueryShowExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListExchange(ctx, req.(*QueryListExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListSenderExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListSenderExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListSenderExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListSenderExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListSenderExchange(ctx, req.(*QueryListSenderExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListDateExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDateExchange(ctx, req.(*QueryListDateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cc.cc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowExchange",
			Handler:    _Query_ShowExchange_Handler,
		},
		{
			MethodName: "ListExchange",
			Handler:    _Query_ListExchange_Handler,
		},
		{
			MethodName: "ListSenderExchange",
			Handler:    _Query_ListSenderExchange_Handler,
		},
		{
			MethodName: "ListDateExchange",
			Handler:    _Query_ListDateExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cc/cc/query.proto",
}
